import { Preset, Application, SimulationMode } from '@/types/simulation';

export const PRESETS: Preset[] = [
  {
    id: 'foucault',
    name: 'Foucault Pendulum',
    description: 'Long pendulum demonstrating Earth\'s rotation. Used in museums worldwide.',
    mode: 'simple',
    application: 'Demonstrates Earth\'s rotation through precession of the swing plane.',
    icon: '🌍',
    params: {
      length: 2.5,
      mass: 3,
      gravity: 9.81,
      initialAngle: Math.PI / 12,
    },
  },
  {
    id: 'resonance',
    name: 'Resonance Catastrophe',
    description: 'Driving frequency matches natural frequency, causing amplitude to grow.',
    mode: 'damped',
    application: 'Shows how bridges and buildings can fail when vibrations match natural frequency.',
    icon: '📈',
    params: {
      length: 1.5,
      mass: 1,
      gravity: 9.81,
      initialAngle: Math.PI / 18,
      damping: 0.05,
      drivingFrequency: 2.56, // Near √(g/L)
      drivingAmplitude: 0.3,
    },
  },
  {
    id: 'chaos',
    name: 'Chaotic Regime',
    description: 'Double pendulum in highly chaotic motion, sensitive to initial conditions.',
    mode: 'double',
    application: 'Demonstrates deterministic chaos - small changes lead to vastly different outcomes.',
    icon: '🌀',
    params: {
      length: 1.2,
      length2: 1.0,
      mass: 1.5,
      mass2: 1,
      gravity: 9.81,
      initialAngle: Math.PI * 0.9,
      initialAngle2: Math.PI * 0.8,
    },
  },
  {
    id: 'seismometer',
    name: 'Seismometer',
    description: 'Pendulum-based detection of ground motion during earthquakes.',
    mode: 'damped',
    application: 'Seismometers use pendulum inertia to measure ground acceleration.',
    icon: '📊',
    params: {
      length: 1.0,
      mass: 2,
      gravity: 9.81,
      initialAngle: 0,
      damping: 0.3,
      drivingFrequency: 5.0,
      drivingAmplitude: 0.8,
    },
  },
  {
    id: 'gravimeter',
    name: 'Gravimeter',
    description: 'Measure local gravity by observing pendulum period.',
    mode: 'simple',
    application: 'T = 2π√(L/g) - measuring period reveals local gravity variations.',
    icon: '⚖️',
    params: {
      length: 1.0,
      mass: 1,
      gravity: 9.81,
      initialAngle: Math.PI / 36,
    },
  },
  {
    id: 'spring-resonance',
    name: 'Spring Resonance',
    description: 'Mass-spring system at resonance frequency.',
    mode: 'spring',
    application: 'Used in vehicle suspensions, vibration isolation, and mechanical filters.',
    icon: '🔧',
    params: {
      mass: 1,
      springConstant: 25,
      damping: 0.1,
      drivingFrequency: 5.0, // √(k/m)
      drivingAmplitude: 2,
      initialDisplacement: 0,
    },
  },
  {
    id: 'normal-modes',
    name: 'Normal Modes',
    description: 'Coupled pendulums showing in-phase and anti-phase oscillations.',
    mode: 'coupled',
    application: 'Fundamental to understanding molecular vibrations and wave propagation.',
    icon: '🔗',
    params: {
      length: 1.5,
      mass: 1,
      gravity: 9.81,
      initialAngle: Math.PI / 6,
      initialAngle2: Math.PI / 6,
      springConstant: 5,
    },
  },
  {
    id: 'energy-transfer',
    name: 'Energy Transfer',
    description: 'Watch energy oscillate between two coupled pendulums.',
    mode: 'coupled',
    application: 'Models energy exchange in coupled systems like molecular bonds.',
    icon: '⚡',
    params: {
      length: 1.5,
      mass: 1,
      gravity: 9.81,
      initialAngle: Math.PI / 4,
      initialAngle2: 0,
      springConstant: 3,
    },
  },
  {
    id: 'overdamped',
    name: 'Overdamped System',
    description: 'High damping prevents oscillation, system returns slowly to equilibrium.',
    mode: 'damped',
    application: 'Door closers and shock absorbers use overdamping for smooth motion.',
    icon: '🚪',
    params: {
      length: 1.5,
      mass: 1,
      gravity: 9.81,
      initialAngle: Math.PI / 4,
      damping: 0.8,
      drivingFrequency: 0,
      drivingAmplitude: 0,
    },
  },
];

export const APPLICATIONS: Application[] = [
  {
    id: 'seismology',
    name: 'Seismometers',
    description: 'Pendulum-based instruments detect and measure ground motion during earthquakes. The pendulum\'s inertia keeps it stationary while the ground moves, allowing precise measurement of seismic waves.',
    icon: '🌋',
    relatedModes: ['damped', 'simple'],
  },
  {
    id: 'gravimetry',
    name: 'Gravimeters',
    description: 'The period T = 2π√(L/g) depends on local gravity. By measuring period and length, scientists calculate local g for geophysical surveys and modeling Earth\'s shape.',
    icon: '🌐',
    relatedModes: ['simple'],
  },
  {
    id: 'foucault',
    name: 'Foucault Pendulum',
    description: 'A long pendulum provides visible, real-time demonstration of Earth\'s rotation. The swing plane appears to rotate as Earth turns beneath it.',
    icon: '🌍',
    relatedModes: ['simple'],
  },
  {
    id: 'clocks',
    name: 'Precision Timekeeping',
    description: 'Pendulum clocks revolutionized timekeeping. The isochronous property (period independent of amplitude for small angles) enables accurate time measurement.',
    icon: '⏰',
    relatedModes: ['simple'],
  },
  {
    id: 'engineering',
    name: 'Structural Engineering',
    description: 'Understanding resonance prevents catastrophic failures like the Tacoma Narrows Bridge. Buildings and bridges are designed to avoid resonance with wind and seismic frequencies.',
    icon: '🏗️',
    relatedModes: ['damped', 'spring'],
  },
  {
    id: 'suspension',
    name: 'Vehicle Suspension',
    description: 'Car suspensions are damped spring systems. Engineers tune spring constants and damping to balance comfort (soft) and handling (stiff).',
    icon: '🚗',
    relatedModes: ['spring', 'damped'],
  },
  {
    id: 'molecular',
    name: 'Molecular Physics',
    description: 'Coupled oscillator models describe molecular vibrations, chemical bonds, and energy transfer. Normal modes explain infrared spectroscopy.',
    icon: '⚛️',
    relatedModes: ['coupled', 'spring'],
  },
  {
    id: 'chaos',
    name: 'Chaos Theory',
    description: 'Double pendulums demonstrate deterministic chaos - systems where tiny differences in initial conditions lead to vastly different outcomes.',
    icon: '🦋',
    relatedModes: ['double'],
  },
];

export const MODE_INFO: Record<SimulationMode, { label: string; desc: string }> = {
  simple: { label: 'Simple', desc: 'Simple Harmonic Motion' },
  double: { label: 'Double', desc: 'Chaotic Double Pendulum' },
  damped: { label: 'Damped', desc: 'Damped & Driven Oscillator' },
  spring: { label: 'Spring', desc: 'Mass-Spring System' },
  coupled: { label: 'Coupled', desc: 'Coupled Oscillators' },
};
